name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      VERSION: '3.4.11'
      SERVERPOD_PASSWORD_database: '0hRDacbGEj6p-z7l7R0zY-7FAamq66qo'
      SERVERPOD_PASSWORD_redis: 'yB0jOkmW0a2tJVeQGmYh5I1-9XFZAKeM'

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'

      - name: Start containers
        working-directory: bibliotheque_numerique_server
        run: docker compose up --quiet-pull --build -d

      - name: Install dependencies
        run: flutter pub get

      - name: Install Serverpod CLI
        run: dart pub global activate serverpod_cli $VERSION

      - name: Run Serverpod generator
        working-directory: bibliotheque_numerique_server
        run: serverpod generate

      - name: Run tests
        working-directory: bibliotheque_numerique_server
        run: dart test

      - name: Stop containers
        if: always()
        working-directory: bibliotheque_numerique_server
        run: docker compose down -v
